### ISSUE TITLE
Share link does not work

### ISSUE THREAD

**Issue by kleenkanteen** [octree-gva/caroster#15] opened 2023-07-08 21:06 UTC
I tried on both chrome and brave browser. When I create an event and click the share button, this box shows for a few seconds then disappears:

![image](https://github.com/octree-gva/caroster/assets/67878058/e69ccb4a-0832-4a5f-b5d7-4d7c7975b6e0)

**Comment by 5ika** [comment] 2023-07-10 08:27
Hi @kleenkanteen, Thank you for your feedback !
This 'share popup' depends on your operating system.
In order to reproduce the problem on our side, can you tell us more information about your OS (MacOS, Windows, other ?) and the version please ?

**Comment by kleenkanteen** [comment] 2023-07-10 15:40
Windows 10

**Comment by 5ika** [comment] 2023-07-11 07:53
Thank you for the details.
When available, the share button runs the native sharing function of your system. If you're using Chrome on Windows, it's supposed to open a popup with sharing options with some installed addons.
It seems that your system fails to load this native function, maybe because of an addon.
Do you have the same problem with other share button ? You can test on this page: https://mdn.github.io/dom-examples/web-share/

**Comment by kleenkanteen** [comment] 2023-07-11 13:35
Same problem, on brave and chrome. And on a fresh install of firefox.

Is the link autogenerated and then shared through this popup? 

Can I get the responsibility to change the share feature so upon clicking share, it instead copies the link and it has a small popup next to the button that says "copied"? Would be nice to contribute.

**Comment by kleenkanteen** [comment] 2023-07-13 20:01
Yes to above?

**Comment by 5ika** [comment] 2023-07-19 07:33
If you have the same problem on https://mdn.github.io/dom-examples/web-share/, the problem is probably with your system or installed addons. The shared link is the current link used in the browser (`window.location.href`).

You can see the relative code here:https://github.com/octree-gva/caroster/blob/main/frontend/hooks/useShare.ts

The code checks if the browser / system supports a native sharing function. If not, it does a mere copy.
We want to keep this behavior, in particular on mobile but we are open to proposal for a better app :-)

**Comment by kleenkanteen** [comment] 2023-07-19 15:09
The button works on my Samsung phone. How about on browsers it just copies
the link and indicates it's been copied?

**Comment by 5ika** [comment] 2023-07-20 07:37
@kleenkanteen It could be a fallback to consider if we can't resolve your problem. But first, could you please tell me if the share button on this page works well on your computer ? https://mdn.github.io/dom-examples/web-share/

**Comment by kleenkanteen** [comment] 2023-07-20 15:05
@5ika Same problem, on brave and chrome. And on a fresh install of firefox.

**Comment by kleenkanteen** [comment] 2023-07-23 17:26
@5ika

**Comment by 5ika** [comment] 2023-07-24 08:59
Thanks @kleenkanteen. We will discuss about the native sharing feature on desktop soon with the team. Until then, you can still copy the URL from your browser in the topbar since it is the same behavior as for the share button.

**Comment by 5ika** [comment] 2023-07-24 09:11
After discussion, we think it's a good idea to remove the native sharing on desktop as you suggested (but keep the functionality on mobile) :+1: 

Would you like to contribue and propose a change ?

**Comment by kleenkanteen** [comment] 2023-07-24 14:37
Sounds good, I will try implementing the change.

**Comment by kleenkanteen** [comment] 2023-07-25 16:02
I want to make a test for this also. A few questions:
1. Are all the tests run on every PR?
2. Why is the folder called E2E testing when it only tests the backend Graphql responses? Is the word E2E misleading?
3. Is caroster a monorepo?
4. I see all Graphql endpoints are tested. Is the share function not able to be tested since this is not something returned by the backend?

**Comment by 5ika** [comment] 2023-07-27 15:15
@kleenkanteen 

1. No, the project lacks some work on tests
2. Yes, it's a misleading name for E2E. I take note to clarify this.
3. It's not a monorepo because `frontend` and `backend` directories are independents. They can be used separately.
4. There is no frontend test yet. We plan to add some soon. Currently, frontend app is tested manually by a few people for each new release.
5. [Strapi](https://strapi.io/) is an headless CMS used for data management. It can use SQLite or Postgres for data storing.
6. Postgres is used for production. SQLite is used for testing.
7. We use Strapi to manage data. Internally, it uses Knex.
8. These are the required variables in `.env`. See [Strapi documentation](https://docs.strapi.io/dev-docs/configurations/server) for details.
```
STRAPI_URL=http://localhost:8080
HOST=0.0.0.0
APP_KEYS="toBeModified1,toBeModified2"
API_TOKEN_SALT=
ADMIN_JWT_SECRET=
JWT_SECRET=
```
9. I see two potential problems for your error:
- Strapi doesn't run on port 1337 locally. You have to update the port used by Strapi or frontend config to target the custom port.
- You have some problem with IPv6 and local access. Force IPv4 could be a solution.

You don't need to configure CORS because the frontend app, based on NextJS, provide an [internal proxy](https://github.com/octree-gva/caroster/blob/caba373d8f5a8ed55487a3f45db95d97bc4dd4a7/frontend/next.config.js#L24) to request Strapi. Backend requests must target http://localhost:3000.

**Comment by kleenkanteen** [comment] 2023-07-27 19:19
1. For 9: This is how my backend `.env` file looks like:

![image](https://github.com/octree-gva/caroster/assets/67878058/cdde4155-e2c0-4ab5-a53b-cdf14efa2e32)

In the original `.env.example` file, the first line pointed to port 8080. I changed it to port 1337 because the frontend `.env.example` file had the first line as `STRAPI_URL=http://localhost:1337`. Before doing that I couldn't open up the strapi admin dashboard. After doing that, I could. So I am assuming me changing the port was correct.

This is how my frontend `.env` looks like:

![image](https://github.com/octree-gva/caroster/assets/67878058/c2e123c5-5c6f-4337-be22-58e5e5249ee1)

2. How do I force IPv4? In the backend `server.ts` file, this is what I have, the default code:

![image](https://github.com/octree-gva/caroster/assets/67878058/d5dd7198-33b3-4f0f-b84c-b0715a48f9b2)

**Comment by 5ika** [comment] 2023-07-28 15:34
Hey @kleenkanteen Thank you for your feedbacks!

1. `8080` port is a mistake. I will update the example .env file.
2. To force IPv4, you can set `127.0.0.1` instead of `localhost`.
3. You don't need to set `NEXTAUTH_URL` variables for Strapi, it is only used by NextJS app. Try to set `NEXTAUTH_URL=http://127.0.0.1:3000/api/nauth` in frontend env vars to avoid possible problem with IPv6. See [Next-auth doc](https://next-auth.js.org/configuration/options#nextauth_url) for details

**Comment by kleenkanteen** [comment] 2023-07-29 04:35
@5ika I replaced every usage of "localhost" with "127.0.0.1" in the backend and frontend. When running both now, the ECONNREFUSED error does not show on the frontend terminal. The api/nauth/session error still occurs:

![image](https://github.com/octree-gva/caroster/assets/67878058/47cbc1d4-c4f5-4988-b62d-f943b51de3d0)

any ideas?

**Comment by 5ika** [comment] 2023-07-31 06:43
Okay, we're almost done :+1: 
You can see the GraphQL error in the browser terminal > Network tab > Response.

![image](https://github.com/octree-gva/caroster/assets/7430173/e7bcc32d-a2f4-4f4b-bbf6-f6b27122ea8a)

Also, requests to `(api/nauth/session` are not supposed to be handled by Strapi but by NextJS (with NextAuth). Maybe there is an error with authentication.

**Comment by kleenkanteen** [comment] 2023-07-31 17:29
Yup, the requests to `/api/nauth/session` go to NextJS. In the frontend `.env` file, the line `NEXTAUTH_URL=http://127.0.0.1:3000/api/nauth` is as it should be.

One config file, not `.env` or `server.ts`, had a random `tt` at the end which I must've added by accident. I removed the `tt`. I forgot the name of the file. I then started up the backend and frontend locally and I was able to create an event:

![image](https://github.com/octree-gva/caroster/assets/67878058/8ecc6fad-2589-4b30-8dce-f0fad5da9bf8)
 
woohoo!

One thing though, in the backend output, I see lines ending with `ERROR`:
![image](https://github.com/octree-gva/caroster/assets/67878058/0f98c418-efb6-4cad-a72a-2f419be55830)

The frontend requests look like this:
![image](https://github.com/octree-gva/caroster/assets/67878058/3dae4bfc-1b82-4f93-94ad-ec5ae26db335)

I am thinking the requests on the graphql network requests that return with a status code of 3xx is listed as `ERROR` in the backend output?

**Comment by kleenkanteen** [comment] 2023-08-03 22:49
@5ika

**Comment by 5ika** [comment] 2023-08-04 06:48
I need to reproduce and investigate to understand why there are 3xx on Graphql requests. Can you see the graphql method used in request details ?

**Comment by kleenkanteen** [comment] 2023-08-04 16:08
Yup. I just started up the backend and frontend and the create event page showed up. The frontend sent 3 graphql read queries upon page load, 2 of them returned with a status code of 3xx. Here is all the frontend requests:

![image](https://github.com/octree-gva/caroster/assets/67878058/8c9ba2b7-e525-4a74-be83-fb40665a92d6)

In the backend terminal output there were 2 corresponding `http: GRAPHQL  (9 ms) ERROR` lines:

![image](https://github.com/octree-gva/caroster/assets/67878058/b827aa9a-c0b2-4339-b759-3e501c27ff35)

For each of the 3 graphql read queries, here is a video of me going through each of them in the network requests:

https://www.loom.com/share/397fc19e1fed4c2ea6fe02648ae7a8b9?sid=22990afc-fc87-453e-9973-eda42c2788f0

I noticed that in each of the 3 requests my browser sends a cookie starting with "rallly-session". rallly is anothe open source project I locally ran the same time I started this whole issue. The cookie is sent for each of the 3 requests though, including the single one that returned 200 OK.

**Comment by kleenkanteen** [comment] 2023-08-06 17:13
Wondering also when will do changes deploy to production?

**Comment by 5ika** [comment] 2023-08-07 08:37
@kleenkanteen After investigation, redirections are linked to i18n with some useless behavior. We will work on this in a next version. The app is not affected by this.

Your changes will be deployed in production during the week.
As your problems are now solved, I close this issue. You can open a new one if needed.

**Closed by 5ika** 2023-08-07 08:37 UTC
Labels: bug

**Comment by 5ika** [comment] 2023-08-16 07:25
Hi @kleenkanteen, your contributions have been deployed to production (https://github.com/octree-gva/caroster/releases/tag/v3.6)
